### PR TITLE
Multiple Emails Bug

### LINKED ISSUE #149: Duplicate email issue
Note: Accidentally made this issue on the wrong repo earlier lol

The bug is that for “Gift A Meal” purchases, it breaks up the gift card purchase into a whole bunch of little gift cards attributed to a third party distributor and then sends a “thank you for your donation!” receipt to the purchaser but since the receipt sending is in the for loop that breaks up the gift cards, it ends up sending a whole bunch of tiny donation receipts to the purchaser.

So if you buy 5 meals for $25 (at $5 a meal), you’ll get 5 receipts for $5 each.

### PR DESCRIPTION
**Pull request by solidiquis**
Closes #149

### CODE REVIEW

File: app/controllers/webhooks_controller.rb [hunk 1]
```diff
@@ -185,5 +182,17 @@ def handle_payment_intent_succeeded(
         end
       end
     end
+
+    if is_donation
+      # Send separate email for each seller.
+      grouped_items = items.group_by { |li| li["seller_id"] }
```
Comment (justintmckibben) [inline app/controllers/webhooks_controller.rb:188]: nit, mind running rubocop -a

File: app/controllers/webhooks_controller.rb [hunk 2]
```diff
@@ -139,19 +141,14 @@ def handle_payment_intent_succeeded(
         merchant_name = Seller.find_by(seller_id: seller_id).name
         case item_json['item_type']
         when 'donation'
+          is_donation ||= true
```
Comment (justintmckibben) [inline app/controllers/webhooks_controller.rb:144]: wow what is this ruby madness lol

File: spec/controllers/webhooks_controller_spec.rb [hunk 3]
```diff
@@ -3,4 +3,48 @@
 require 'rails_helper'
 
 RSpec.describe WebhooksController, type: :controller do
+  describe "POST create" do
+    let!(:payment_intent) do
+      create :payment_intent, :with_line_items, square_payment_id: 'square-id', square_location_id: "OIJWEOIFJEOIFJ"
```
Comment (justintmckibben) [inline spec/controllers/webhooks_controller_spec.rb:8]: could you use ENV['SQUARE_LOCATION_ID']?

File: app/controllers/webhooks_controller.rb (hunk 2 above)
Comment (jacoblb64) [inline app/controllers/webhooks_controller.rb:144]: Maybe this is a ruby quirk i’m not familiar with, but why are we setting this to nil initially instead of false, then `||=`’ing it to true instead of just setting it?

Comment (solidiquis) [reply app/controllers/webhooks_controller.rb:144]: Because if I initially set it to false, then set it to true in the loop without using the conditional assignment operator, is_donation will keep getting re-assigned to true after every loop, which is like negligibly more time expensive, but still haha. I COULD use an if-statement but would look kind of ugly haha. Open to discussion though!

Screen Shot 2020-06-17 at 3 58 15 PM

Comment (jacoblb64) [reply app/controllers/webhooks_controller.rb:144]: Interesting, makes sense that `||=` is faster than a raw assignment. Where’s the advantage come from the initial `nil` vs `false` though?

Comment (solidiquis) [reply app/controllers/webhooks_controller.rb:144]: Ahhh I had assumed that if a = false then a ||= true would still give a = false but turns out that isn't the case haha. I'll change that. Thanks man!
